### ISSUE TITLE
Uint64.toString fails for large numbers

### ISSUE THREAD

**Issue by danvk** [jDataView/jDataView#66]
For example:

```javascript
new jDataView.Uint64(12345678, 12345678).toString()  // "53024283269292370"
```

Whereas in Python, with arbitrary-precision numbers, I get:

```python
print 12345678 * 2**32 + 12345678  # 53024283269292366
```

These differ in the last decimal.

The `.valueOf()` method has to round off, but there's no reason `.toString()` should.

**Comment by RReverser** [comment]
Oh I missed this. Yeah, it shouldn't of course, but implementation is not very simple and not high priority. Feel free to send PRs though.

**Comment by danvk** [comment]
Sent out #72 -- let me know what you think.
