### ISSUE TITLE
Using jDataView in chrome throws Uncaught ReferenceError: NODE is not defined

### ISSUE THREAD

**Issue by ManuelB** [jDataView/jDataView#67]
var compatibility = {
	// NodeJS Buffer in v0.5.5 and newer
	NodeBuffer: NODE && 'Buffer' in global,
	DataView: 'DataView' in global,
	ArrayBuffer: 'ArrayBuffer' in global,
	PixelData: BROWSER && 'CanvasPixelArray' in global && !('Uint8ClampedArray' in global) && 'document' in global
};

Uncaught ReferenceError: NODE is not defined(anonymous function) @ jdataview.js:4

**Comment by RReverser** [comment]
Apparently you're including an incorrect version of library. Please use https://jdataview.github.io/dist/jdataview.js from CDN or include version from `/dist/browser` folder manually.

**Comment by ManuelB** [comment]
@RReverser thanks a lot. It is working now.

**Comment by testn** [comment]
How can I use ```"jdataview": "^2.5.0"``` in vite then. I still encounter this issue.
