### ISSUE TITLE
Better support for negative bitLength

### ISSUE THREAD

**Issue by SoniEx2** [jDataView/jDataView#68]
When reading bits, I'd like to be able to specify negative bitLength, to read from the end instead of from the start.

**Comment by RReverser** [comment]
From the end of what?

**Comment by SoniEx2** [comment]
From the end of the byte.

**Comment by RReverser** [comment]
Not very obvious - could be the end of the buffer as well. It sounds like this should be already doable via combination of `skip` + reading bits, if you want to ignore those in the beginning.

**Comment by SoniEx2** [comment]
It doesn't work right.

```js
var jd = new jDataView(2);
jd.writeUint8(0xFE); // 0b11111110
jd.writeUint8(0xFE); // 0b11111110
for (;;) {
  console.log(jd.getUnsigned(-1));
}
```

Output:
```
0
63
31
15
7
3
1
0
0
63
31
15
7
3
1
0
0
```

(Did I just put in 16 bits and read back 17 bits? Apparently. And they weren't even right.)

**Comment by RReverser** [comment]
You are reading negative length - as I said above, this is not supported. You should be using combination of `skip` + reading bits if you want to read only some bits in the end of byte.

**Comment by SoniEx2** [comment]
I want to read the bits backwards. (Lovely compression format I'm dealing with does little-endian BIT order)

**Comment by RReverser** [comment]
Oh my... :( Well, what I can recommend is to look into [jBinary](https://github.com/jDataView/jBinary) and simply define custom type that would perform bit-by-bit reversion. This is not kind of stuff that is supported natively on any platforms or even widely used, so I don't think it should be in scope of jDataView, but should be pretty easy to implement as custom reusable type.

**Comment by SoniEx2** [comment]
Well in assembly you just shift left and test the carry bit...

**Comment by RReverser** [comment]
Well if you need only one last bit, then it's easy here as well - just `readUint8() & 1`.

**Comment by SoniEx2** [comment]
Why was this closed?

**Comment by RReverser** [comment]
I replied above that it's both already possible to do what you want (and even provided how), and adding it to base API just for sugar in specific cases doesn't make much sense.
