### ISSUE TITLE
Use backing buffer/view's methods when available.

### ISSUE THREAD

**Issue by SoniEx2** [jDataView/jDataView#69]
If DataView is available and the backing buffer is an ArrayView, use DataView's methods (with some indirection to change the internal offsets, I guess) instead.

This should increase performance.

**Comment by RReverser** [comment]
> This should increase performance.
Not really - DataView is in fact slower than manual access, just easier to wrap when available.

**Comment by RReverser** [comment]
Nevertheless, what exactly are you proposing? DataView is already used when available.

**Comment by SoniEx2** [comment]
> Nevertheless, what exactly are you proposing? DataView is already used when available.

Wait... how? O_o

**Comment by RReverser** [comment]
> But isn't it native?

It is native, but unfortunately (or fortunately) "native" is far not always synonym for "faster", especially when it's just another API level for same low-level stuff :)

> Wait... how? O_o

I rather expected that you will explain why you decided it's not used...

**Comment by RReverser** [comment]
Here's a "proof" execution in browser where DataView is privately used for initially regular array of bytes: http://requirebin.com/?gist=142472071d47ccdcd633

jDataView automatically uses Buffer / DataView / ArrayBuffer / regular arrays stopping on first one which is supported on current platform.
