### ISSUE TITLE
Bitfield API ignores endianness.

### ISSUE THREAD

**Issue by griffinmilsap** [jDataView/jDataView#76]
As it stands, the Bitfield API does not care about the value of _littleEndian, which results in unexpected behavior.  Currently, the Bitfield API assumes big endian data.

**Comment by RReverser** [comment]
Endianness for bitfields doesn't make any sense, as you can't read parts of bytes in reverse direction (which is what little endian is). E.g. if you try to read 18 bits, which parts of which bytes should be read in that case? There would be lots of confusion, no matter which particular answer you choose. Instead, try to order bitfields in the stream order.

**Comment by griffinmilsap** [comment]
Aye, I agree entirely.  That said, my current problem has a bytestream that is transmitted in little endian byte order, but bitfields within that re-ordered bytestream function per-normal.  Its kind of non-standard, so its probably not worth confounding the jDataView for it.  I'll manually twiddle some bits/bytes.
