### ISSUE TITLE
untar demo intersperses chunks of JavaScript in textareas

### ISSUE THREAD

**Issue by skierpage** [jDataView/jDataView#81]
In both Firefox (Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0) and Chromium (57.0.2987.133 (Developer Build) Fedora Project (64-bit)), the nifty http://jdataview.github.io/jDataView/untar/ demo intersperses textareas with the tar file's contents. In between the objects for "src/outro.js" and "src/css.js" is a textarea containing just
```
'}}(window);"
```
then after that there are several textareas containing chunks of
``` js
(function( jQuery ) {
...
})( jQuery );
```
code. I see no warnings in the JavaScript console.

**Comment by RReverser** [comment]
It's not really a bug, just the way demo works :) If you look into the code, you can see that it intentionally outputs metadata in `<pre>` tags and actual files content in `<textarea>` tags (and yes, that `.tar` archive really has JavaScript files inside).
