### ISSUE TITLE
dataview constructor argument offset is invalid

### ISSUE THREAD

**Issue by publicocean0** [jDataView/jDataView#82]
how can solve this error in IE11?

**Comment by publicocean0** [comment]
new Dataview (arraybuffer,number) is not right?

**Comment by RReverser** [comment]
If you want to get help, please post details - code, expected results, actual results etc.

**Comment by publicocean0** [comment]
it is very simple in this case. You can go in your demo... it gaves the same exception using ie11 loading any file. Anyway i will pass the exact point in the code.
Sincerelly it is a bug very strange. The input types seams correct.  I tried also to add a dataview shim but nothing. The absurd thing is if i execute the same operation in a empty html page(with same parameters) it works. Maybe i m working too much in this period i have hallucinations :)

**Comment by publicocean0** [comment]
in the while i can tell you: 
there is a page where it script is online. 
http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html

**Comment by RReverser** [comment]
@publicocean0 So it looks like you're using regular built-in `DataView`, not `jDataView` that this repo provides?

**Comment by publicocean0** [comment]
ah your class has a different name ... uhmm if i override dataview object with your version can it work?

**Comment by publicocean0** [comment]
the test above dont work :( 
the problem seams harder that i foresaw

**Comment by publicocean0** [comment]
1) i can make instruction above because it generate a loop. 
2) i used now jDataView but now it give exception inside jdataView ... same error in the point where call the native one

**Comment by publicocean0** [comment]
in debug with ie11
in line new nativeDataView(buffer, byteOffset, byteLength)
typeof byteOffset = number,value=0
typeof byteLength = number,value=0
typeof buffer = object , value = [object ArrayBuffer]{byteLength: 0}

**Comment by publicocean0** [comment]
ah now i understand ahaahaah
