### ISSUE TITLE
Getting an error only after minification of dist/browser/jdataview.js?

### ISSUE THREAD

**Issue by cmdcolin** [jDataView/jDataView#83]
When I package dist/browser/jdataview.js in a minified build (run it through google closure compiler with dojo), it ends up that the module that is given to me in the AMD is an empty Object e.g. {} from chrome devtools

This is a fairly weird because the unminified build does not have this problem? I managed to boil it down into a pretty simple test to try, I guess I have only tried dojo so far on it but could try other AMD loaders perhaps https://github.com/cmdcolin/jdataview_tester

Screenshots from unminified

![virtualbox_lubuntu_13_07_2017_01_25_41](https://user-images.githubusercontent.com/6511937/28151835-258ad1c2-676b-11e7-9f12-8d3083183489.png)

Screenshot after minified

![virtualbox_lubuntu_13_07_2017_01_32_26](https://user-images.githubusercontent.com/6511937/28151839-2c07933c-676b-11e7-998a-c066ffbfc663.png)

Any ideas? I guess I realize this might not be a jdataview specific issue so I cross posted here https://stackoverflow.com/questions/45072183/jdataview-module-not-working-in-amd-after-running-through-minification-with-goog

**Comment by RReverser** [comment]
It is weird indeed, although I haven't used AMD for a while. Did you try loading https://jdataview.github.io/dist/jdataview.js itself or some other version?

**Comment by cmdcolin** [comment]
@RReverser yep just the same as that one, comes from bower

**Comment by RReverser** [comment]
Oh, just reread SO question, so you ran Closure Compiler on that minified source yourself afterwards? Then it can be some configuration issue, as Closure Compiler, especially in advanced mode, breaks scripts very often unless they have specific annotations. It's best to exclude jDataView from such minification.

**Comment by cmdcolin** [comment]
Gotcha. I kind of figured the double-minification wasn't such a good idea. Thanks for checking it out 

I'll close for now and post back if I find any updates (current fix is just using an older version of jdataview)
