### ISSUE TITLE
Cannot use 'in' operator to search for 'Buffer' in undefined

### ISSUE THREAD

**Issue by samueleastdev** [jDataView/jDataView#87]
Hi,

I am trying to update this plugin https://github.com/chemoish/videojs-bif that uses jDataView to analyze a bif image.

But I keep running into this error.

Cannot use 'in' operator to search for 'Buffer' in undefined
In jDataView it is stopping at this line.

NodeBuffer: !0 && "Buffer" in global,
Seems to be an issue with the global.

You can see the file that calls the jDataView here.

https://github.com/chemoish/videojs-bif/blob/master/src/parser.js

It works on the old version but not the latest one I am just a bit confused with how to resolve this error been stuck on it for a while now.

Maybe it has something to do with the way the new video-js plugin generator is setup https://github.com/videojs/generator-videojs-plugin

Not sure any help would be appreciated thanks.

**Comment by davidenke** [comment]
@samueleastdev did you solve that issue?

**Comment by Akkriden** [comment]
Was anybody able to solve this?

**Comment by leomurca** [comment]
I'm having the same issue!

**Comment by medi11** [comment]
It's the same thing for me.

**Comment by InScopeTech** [comment]
Why is the issue closed? People (including me) have the same problem.
